language: php
php:
  - 5.6
  - 7
sudo: false
install:
  - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.zip
  - unzip -qq sonar-scanner-2.6.zip
before_script:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jre
  - echo "sonar.host.url=http://sonarqube.it.dh-karlsruhe.de" >> sonar-scanner-2.6/conf/sonar-scanner.properties
  - mv .env.behat.travis .env.behat
  - mv .env.travis .env
  - chmod -R 777 storage
  - touch storage/database.sqlite
  - composer self-update
  - composer update --no-scripts
  - composer update
  - php artisan migrate --seed --force

script:
  - phpunit tests/
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml
  - sonar-scanner-2.6/bin/sonar-scanner