language: php
php:
  - 7
  - 5.6
sudo: false

addons:
    code_climate:
        repo_token: ea38ff2c19d0e7030f8acb35caa9963972a00d503c80641bce6bccf2e9ab7f33

jdk: openjdk7

before_install:
  - composer self-update
  - composer update --no-scripts
  - composer update

install:
  - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.zip
  - unzip -qq sonar-scanner-2.6.zip

before_script:
  - echo "sonar.host.url=http://sonarqube.it.dh-karlsruhe.de" >> sonar-scanner-2.6/conf/sonar-scanner.properties
  - mv .env.behat.travis .env.behat
  - mv .env.travis .env
  - chmod -R 777 storage
  - touch storage/database.sqlite
  - php artisan migrate --seed --force

script:
  - vendor/bin/phpunit tests/
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml

after_script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then sonar-scanner-2.6/bin/sonar-scanner; fi
  - vendor/bin/test-reporter

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then curl https://bot.bomberus.de/$api_key/deployment.php > /dev/null; fi

after_failure:
  - ./.send_ticket.sh