language: php
php:
  - 5.6
  - 7
sudo: false
before_script:
  - mv .env.behat.travis .env.behat
  - chmod -R 777 storage
  - touch storage/acceptance.sqlite
  - composer self-update
  - composer update --no-scripts
  - composer update
  - php artisan migrate --seed --force


script:
  - phpunit tests/
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml