language: php
php:
  - 7
sudo: false

addons:
    code_climate:
        repo_token: ea38ff2c19d0e7030f8acb35caa9963972a00d503c80641bce6bccf2e9ab7f33

jdk: openjdk7



script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then sonar-scanner-2.6/bin/sonar-scanner; fi

after_script:
  - vendor/bin/test-reporter

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then curl https://bot.bomberus.de/$api_key/deployment.php > /dev/null; fi

after_failure:
  - ./.send_ticket.sh